### YamlMime:BusinessCentralApplicationObject
fqName: System.Environment.Configuration."Checklist Banner"
alId: ID 3728
namespace: System.Environment.Configuration
baseKind: Codeunit
kind: Codeunit
parent: N:Module::System_Application::Namespace::System.Environment.Configuration
langs:
- al
seeAlso:
- '[Codeunit](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-codeunit-object)'
objectProperties:
- name: Access
  value: Public
  promoted: false
- name: Description
  value: Public events for the Checklist Banner
  promoted: false
- name: InherentEntitlements
  value: X
  promoted: false
- name: InherentPermissions
  value: X
  promoted: false
commentId: O:Codeunit::System#Environment#Configuration#Checklist Banner
summary: Provides functionality to customize the Checklist Banner
name: '"Checklist Banner"'
uid: O:Codeunit::System#Environment#Configuration#Checklist_Banner
