### YamlMime:BusinessCentralApplicationObject
fqName: System.Environment.Configuration."Spotlight Tour"
alId: ID 3727
namespace: System.Environment.Configuration
baseKind: Codeunit
kind: Codeunit
parent: N:Module::System_Application::Namespace::System.Environment.Configuration
langs:
- al
seeAlso:
- '[Codeunit](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-codeunit-object)'
methods:
- syntax:
    content: 'procedure Start(PageId: Integer, SpotlightTourType: Enum "Spotlight Tour Type", Title1: Text, Text1: Text, Title2: Text, Text2: Text)'
    parameters:
    - id: PageId
      description: Page to run tour on.
      parameterType:
        name: Integer
        isExternal: true
    - id: SpotlightTourType
      description: Type of tour.
      parameterType:
        internalReference: O:Enum::System#Environment#Configuration#Spotlight_Tour_Type
        name: System.Environment.Configuration."Spotlight Tour Type"
        isExternal: false
    - id: Title1
      description: Title for step 1.
      parameterType:
        name: Text
        isExternal: true
    - id: Text1
      description: Text for step 1.
      parameterType:
        name: Text
        isExternal: true
    - id: Title2
      description: Title for step 2.
      parameterType:
        name: Text
        isExternal: true
    - id: Text2
      description: Text for step 2.
      parameterType:
        name: Text
        isExternal: true
  summary: Start spotlight tour on specific page.
  name: Start
  uid: M:Codeunit::System#Environment#Configuration#Spotlight_Tour.Start(Integer,Enum::System#Environment#Configuration#Spotlight_Tour_Type,Text,Text,Text,Text)
commentId: O:Codeunit::System#Environment#Configuration#Spotlight Tour
summary: Provides functionality to use spotlight tours
name: '"Spotlight Tour"'
uid: O:Codeunit::System#Environment#Configuration#Spotlight_Tour
