### YamlMime:BusinessCentralApplicationObject
fqName: System.Environment.Configuration."Feature Management"
namespace: System.Environment.Configuration
baseKind: Interface
kind: Interface
parent: N:Module::System_Application::Namespace::System.Environment.Configuration
langs:
- al
seeAlso:
- '[Interface](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-interfaces-in-al)'
methods:
- syntax:
    content: 'procedure GetData(IncludeFeatureKeys: List of [Text[50]], ExcludeFeatureKeys: List of [Text[50]], var FeatureKeyBuffer: Record "Feature Key Buffer" temporary): Integer'
    parameters:
    - id: IncludeFeatureKeys
      parameterType:
        name: List of [Text[50]]
        isExternal: true
    - id: ExcludeFeatureKeys
      parameterType:
        name: List of [Text[50]]
        isExternal: true
    - id: FeatureKeyBuffer
      parameterType:
        name: Record "Feature Key Buffer" temporary
        isExternal: true
    return:
      returnType:
        name: Integer
        isExternal: true
  name: GetData
  uid: M:Interface::System#Environment#Configuration#Feature_Management.GetData(List_of_[Text],List_of_[Text],Feature_Key_Buffer@):Integer
- syntax:
    content: 'procedure GetFeatureKey(FeatureId: Text[50], TempFeatureKey: __MissingTypeSymbol__): Boolean'
    parameters:
    - id: FeatureId
      parameterType:
        name: Text[50]
        isExternal: true
    - id: TempFeatureKey
      parameterType:
        name: __MissingTypeSymbol__
        isExternal: true
    return:
      returnType:
        name: Boolean
        isExternal: true
  name: GetFeatureKey
  uid: M:Interface::System#Environment#Configuration#Feature_Management.GetFeatureKey(Text[50],__MissingSymbol__@):Boolean
- syntax:
    content: 'procedure SetEnabled(TempFeatureKey: __MissingTypeSymbol__): Boolean'
    parameters:
    - id: TempFeatureKey
      parameterType:
        name: __MissingTypeSymbol__
        isExternal: true
    return:
      returnType:
        name: Boolean
        isExternal: true
  name: SetEnabled
  uid: M:Interface::System#Environment#Configuration#Feature_Management.SetEnabled(__MissingSymbol__):Boolean
- syntax:
    content: 'procedure GenerateDependencies(var FeatureKeyBuffer: Record "Feature Key Buffer" temporary, var FeatureDependency: Record "Feature Dependency" temporary): Boolean'
    parameters:
    - id: FeatureKeyBuffer
      description: the record set of the available feature keys
      parameterType:
        name: Record "Feature Key Buffer" temporary
        isExternal: true
    - id: FeatureDependency
      description: returned the record set of the dependencies to add
      parameterType:
        name: Record "Feature Dependency" temporary
        isExternal: true
    return:
      description: if any feature dependency was generated
      returnType:
        name: Boolean
        isExternal: true
  summary: >-
    Fills the temporary table "Feature Dependency" stored in the single instance codeunit "Feature Dependency Management".

    Add new feature dependencies by passing DependentFeatureId and ParentFeatureID,

    FeatureKeyBuffer is passed to control data consistency:
      FeatureDependency.New(FeatureKeyBuffer, DependentFeatureId, ParentFeatureID);
  name: GenerateDependencies
  uid: M:Interface::System#Environment#Configuration#Feature_Management.GenerateDependencies(Feature_Key_Buffer@,Feature_Dependency@):Boolean
commentId: O:Interface::System#Environment#Configuration#Feature Management
summary: >-
  Interface that defines methods for linking tables "Feature Key Buffer" and "Feature Key".

  The default implementation uses the system table "Feature Key" as a source,

  but another implementation uses a temporary table "Feature Key" to delink Feature Management UX from the read-only virtual table.
name: '"Feature Management"'
uid: O:Interface::System#Environment#Configuration#Feature_Management
