### YamlMime:BusinessCentralApplicationObject
fqName: System.Environment.Configuration."Feature Data Update"
namespace: System.Environment.Configuration
baseKind: Interface
kind: Interface
parent: N:Module::System_Application::Namespace::System.Environment.Configuration
langs:
- al
seeAlso:
- '[Interface](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-interfaces-in-al)'
methods:
- syntax:
    content: 'procedure IsDataUpdateRequired(): Boolean'
    return:
      description: true if there is data to update
      returnType:
        name: Boolean
        isExternal: true
  summary: Searches the database for data that must be updated before the feature can be enabled.
  name: IsDataUpdateRequired
  uid: M:Interface::System#Environment#Configuration#Feature_Data_Update.IsDataUpdateRequired:Boolean
- syntax:
    content: procedure ReviewData()
  summary: Opens the page showing the list of tables with counted records that require update.
  name: ReviewData
  uid: M:Interface::System#Environment#Configuration#Feature_Data_Update.ReviewData
- syntax:
    content: 'procedure UpdateData(FeatureDataUpdateStatus: Record "Feature Data Update Status")'
    parameters:
    - id: FeatureDataUpdateStatus
      description: the feature update status record
      parameterType:
        name: Record "Feature Data Update Status"
        isExternal: true
  summary: Runs the process that updates data for the feature.
  name: UpdateData
  uid: M:Interface::System#Environment#Configuration#Feature_Data_Update.UpdateData(Feature_Data_Update_Status)
- syntax:
    content: 'procedure AfterUpdate(FeatureDataUpdateStatus: Record "Feature Data Update Status")'
    parameters:
    - id: FeatureDataUpdateStatus
      description: the feature update status record
      parameterType:
        name: Record "Feature Data Update Status"
        isExternal: true
  summary: Method is called after the update is complete, e.g. to complete the setup for the feature.
  name: AfterUpdate
  uid: M:Interface::System#Environment#Configuration#Feature_Data_Update.AfterUpdate(Feature_Data_Update_Status)
- syntax:
    content: 'procedure GetTaskDescription(): Text'
    return:
      description: The process description
      returnType:
        name: Text
        isExternal: true
  summary: >-
    Retruns the detailed description of the data update required for the feature.

    It is shown of the "Schedule Feature Data Update" page to explain the user what is going to happen.
  name: GetTaskDescription
  uid: M:Interface::System#Environment#Configuration#Feature_Data_Update.GetTaskDescription:Text
commentId: O:Interface::System#Environment#Configuration#Feature Data Update
summary: Interface defines methods for feature data update task management.
name: '"Feature Data Update"'
uid: O:Interface::System#Environment#Configuration#Feature_Data_Update
