### YamlMime:BusinessCentralApplicationObject
fqName: System.Environment."Client Type Mgt. - Objects"
alId: ID 4030
namespace: System.Environment
baseKind: PermissionSet
kind: PermissionSet
parent: N:Module::System_Application::Namespace::System.Environment
langs:
- al
seeAlso:
- '[Permission Set](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-permissionset-object)'
objectProperties:
- name: Assignable
  value: "False"
  promoted: false
- name: ObsoleteState
  value: Pending
  promoted: false
- name: ObsoleteReason
  value: This permission set is replaced with inherent permissions and is no longer needed.
  promoted: false
- name: ObsoleteTag
  value: "22.0"
  promoted: false
commentId: O:PermissionSet::System#Environment#Client Type Mgt# - Objects
name: '"Client Type Mgt. - Objects"'
obsoletion:
  state: pending
  reason: This permission set is replaced with inherent permissions and is no longer needed.
  version: "22.0"
uid: O:PermissionSet::System#Environment#Client_Type_Mgt#_-_Objects
