### YamlMime:BusinessCentralApplicationObject
fqName: System.Environment.Configuration."System Initialization - Exec"
alId: ID 150
namespace: System.Environment.Configuration
baseKind: PermissionSet
kind: PermissionSet
parent: N:Module::System_Application::Namespace::System.Environment.Configuration
langs:
- al
seeAlso:
- '[Permission Set](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-permissionset-object)'
objectProperties:
- name: Access
  value: Public
  promoted: false
- name: Assignable
  value: "False"
  promoted: false
- name: IncludedPermissionSets
  value: '"AAD User Management - Exec"'
  promoted: false
commentId: O:PermissionSet::System#Environment#Configuration#System Initialization - Exec
name: '"System Initialization - Exec"'
uid: O:PermissionSet::System#Environment#Configuration#System_Initialization_-_Exec
