### YamlMime:BusinessCentralApplicationObject
fqName: System.Environment.Configuration."Feature Mgt. - Admin"
alId: ID 2615
namespace: System.Environment.Configuration
baseKind: PermissionSet
kind: PermissionSet
parent: N:Module::System_Application::Namespace::System.Environment.Configuration
langs:
- al
seeAlso:
- '[Permission Set](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-permissionset-object)'
objectProperties:
- name: Access
  value: Public
  promoted: false
- name: Assignable
  value: "True"
  promoted: false
- name: Caption
  value: Feature Management - Admin
  promoted: false
- name: IncludedPermissionSets
  value: '"Feature Key - Admin"'
  promoted: false
commentId: O:PermissionSet::System#Environment#Configuration#Feature Mgt# - Admin
summary: This permission set is required to turn a feature on or off. It can be assigned to users to give full access to the Feature Management functionality.
name: '"Feature Mgt. - Admin"'
uid: O:PermissionSet::System#Environment#Configuration#Feature_Mgt#_-_Admin
