### YamlMime:BusinessCentralApplicationObject
fqName: System.Environment.Configuration."Navigation Bar Subs. - Objects"
alId: ID 1818
namespace: System.Environment.Configuration
baseKind: PermissionSet
kind: PermissionSet
parent: N:Module::System_Application::Namespace::System.Environment.Configuration
langs:
- al
seeAlso:
- '[Permission Set](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-permissionset-object)'
objectProperties:
- name: Access
  value: Public
  promoted: false
- name: Assignable
  value: "False"
  promoted: false
- name: ObsoleteState
  value: Pending
  promoted: false
- name: ObsoleteReason
  value: This permission set is replaced with inherent permissions and is no longer needed.
  promoted: false
- name: ObsoleteTag
  value: "22.0"
  promoted: false
commentId: O:PermissionSet::System#Environment#Configuration#Navigation Bar Subs# - Objects
name: '"Navigation Bar Subs. - Objects"'
obsoletion:
  state: pending
  reason: This permission set is replaced with inherent permissions and is no longer needed.
  version: "22.0"
uid: O:PermissionSet::System#Environment#Configuration#Navigation_Bar_Subs#_-_Objects
