### YamlMime:BusinessCentralApplicationObject
fqName: System.Environment.WelcomeWizard
namespace: System.Environment
baseKind: ControlAddIn
kind: ControlAddIn
parent: N:Module::System_Application::Namespace::System.Environment
langs:
- al
seeAlso:
- '[ControlAddIn](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-control-addin-object)'
methods:
- syntax:
    content: 'procedure Initialize(Title: Text, Subtitle: Text, Explanation: Text, Intro: Text, IntroDescription: Text, GetStarted: Text, GetStartedDescription: Text, GetHelp: Text, GetHelpDescription: Text, RoleCenters: Text, RoleCentersDescription: Text, RoleCenter: Text, LegalDescription: Text)'
    parameters:
    - id: Title
      description: Welcome Wizard Title
      parameterType:
        name: Text
        isExternal: true
    - id: Subtitle
      description: Welcome Wizard Sub Title
      parameterType:
        name: Text
        isExternal: true
    - id: Explanation
      description: Information description
      parameterType:
        name: Text
        isExternal: true
    - id: Intro
      description: Intro text
      parameterType:
        name: Text
        isExternal: true
    - id: IntroDescription
      description: Description for the intro video
      parameterType:
        name: Text
        isExternal: true
    - id: GetStarted
      description: Get started text
      parameterType:
        name: Text
        isExternal: true
    - id: GetStartedDescription
      description: Description for the get started video
      parameterType:
        name: Text
        isExternal: true
    - id: GetHelp
      description: Find Help Text
      parameterType:
        name: Text
        isExternal: true
    - id: GetHelpDescription
      description: Description for the find help video
      parameterType:
        name: Text
        isExternal: true
    - id: RoleCenters
      description: Role Centers Text
      parameterType:
        name: Text
        isExternal: true
    - id: RoleCentersDescription
      description: Description about the role centers
      parameterType:
        name: Text
        isExternal: true
    - id: RoleCenter
      description: Role center
      parameterType:
        name: Text
        isExternal: true
    - id: LegalDescription
      description: Description explaining demo data is for demonstration purposes
      parameterType:
        name: Text
        isExternal: true
  summary: Function that initializes the WelcomeWizard API
  name: Initialize
  uid: M:ControlAddIn::System#Environment#WelcomeWizard.Initialize(Text,Text,Text,Text,Text,Text,Text,Text,Text,Text,Text,Text,Text)
- syntax:
    content: 'procedure LoadFlows(EnvironmentId: Text)'
    parameters:
    - id: EnvironmentId
      description: Environmnet ID
      parameterType:
        name: Text
        isExternal: true
  summary: Function that loads the embedded Welcome Wizard into a container on a webpage
  name: LoadFlows
  uid: M:ControlAddIn::System#Environment#WelcomeWizard.LoadFlows(Text)
- syntax:
    content: 'procedure UpdateProfileId(ChangedProfileId: Text)'
    parameters:
    - id: ChangedProfileId
      description: Profile ID
      parameterType:
        name: Text
        isExternal: true
  summary: Function that updates the Role Center Profile ID
  name: UpdateProfileId
  uid: M:ControlAddIn::System#Environment#WelcomeWizard.UpdateProfileId(Text)
- syntax:
    content: 'procedure LoadTemplates(EnvironmentId: Text, SearchTerm: Text, PageSize: Text, Destination: Text)'
    parameters:
    - id: EnvironmentId
      description: Environmnet ID
      parameterType:
        name: Text
        isExternal: true
    - id: SearchTerm
      description: Filters templates matching the search term
      parameterType:
        name: Text
        isExternal: true
    - id: PageSize
      description: Number of templates to be displayed in the container
      parameterType:
        name: Text
        isExternal: true
    - id: Destination
      description: Determines page that opens when one selects a template
      parameterType:
        name: Text
        isExternal: true
  summary: Function that loads embedded WelcomeWizard templates into a container on a webpage
  name: LoadTemplates
  uid: M:ControlAddIn::System#Environment#WelcomeWizard.LoadTemplates(Text,Text,Text,Text)
commentId: O:ControlAddIn::System#Environment#WelcomeWizard
name: WelcomeWizard
uid: O:ControlAddIn::System#Environment#WelcomeWizard
