### YamlMime:BusinessCentralApplicationObject
fqName: System.Environment.Configuration."User Settings FactBox"
alId: ID 9208
namespace: System.Environment.Configuration
baseKind: Page
kind: Page
parent: N:Module::System_Application::Namespace::System.Environment.Configuration
langs:
- al
sourceTableType:
  internalReference: O:Table::System#Environment#Configuration#User_Settings
  name: System.Environment.Configuration."User Settings"
  isExternal: false
seeAlso:
- '[Page](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-page-object)'
objectProperties:
- name: Caption
  value: User Settings
  promoted: false
- name: Editable
  value: "False"
  promoted: false
- name: PageType
  value: CardPart
  promoted: true
- name: SourceTable
  value: "9172"
  promoted: true
  xrefType:
    internalReference: O:Table::System#Environment#Configuration#User_Settings
    name: System.Environment.Configuration."User Settings"
    isExternal: false
- name: SourceTableTemporary
  value: "True"
  promoted: false
commentId: O:Page::System#Environment#Configuration#User Settings FactBox
summary: A Factbox that shows the settings of a given user.
name: '"User Settings FactBox"'
uid: O:Page::System#Environment#Configuration#User_Settings_FactBox
