### YamlMime:BusinessCentralApplicationObject
fqName: System.Environment.Configuration."Manual Setup"
alId: ID 1875
namespace: System.Environment.Configuration
baseKind: Page
kind: Page
parent: N:Module::System_Application::Namespace::System.Environment.Configuration
langs:
- al
sourceTableType:
  name: System.Environment.Configuration."Guided Experience Item"
  isExternal: true
seeAlso:
- '[Page](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-page-object)'
objectProperties:
- name: Extensible
  value: "False"
  promoted: true
- name: ApplicationArea
  value: '#All'
  promoted: false
- name: Caption
  value: Manual Setup
  promoted: false
- name: DeleteAllowed
  value: "False"
  promoted: false
- name: InsertAllowed
  value: "False"
  promoted: false
- name: ModifyAllowed
  value: "False"
  promoted: false
- name: PageType
  value: List
  promoted: true
- name: SourceTable
  value: "1990"
  promoted: true
- name: SourceTableTemporary
  value: "True"
  promoted: false
- name: UsageCategory
  value: Administration
  promoted: false
- name: ContextSensitiveHelpPage
  value: setup
  promoted: false
- name: Permissions
  value: tabledata "Guided Experience Item" = r
  promoted: false
commentId: O:Page::System#Environment#Configuration#Manual Setup
summary: This page shows all registered manual setups.
name: '"Manual Setup"'
uid: O:Page::System#Environment#Configuration#Manual_Setup
