### YamlMime:BusinessCentralApplicationObject
fqName: System.Azure.Identity."Plan Configuration Card"
alId: ID 9069
namespace: System.Azure.Identity
baseKind: Page
kind: Page
parent: N:Module::System_Application::Namespace::System.Azure.Identity
langs:
- al
sourceTableType:
  name: System.Azure.Identity."Plan Configuration"
  isExternal: true
seeAlso:
- '[Page](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-page-object)'
objectProperties:
- name: DataCaptionExpression
  value: Rec."Plan Name"
  promoted: false
- name: Caption
  value: License Configuration
  promoted: false
- name: Editable
  value: "True"
  promoted: false
- name: PageType
  value: Card
  promoted: true
- name: SourceTable
  value: "9017"
  promoted: true
- name: Extensible
  value: "True"
  promoted: true
- name: Permissions
  value: tabledata "Plan Configuration" = rimd
  promoted: false
- name: ContextSensitiveHelpPage
  value: ui-how-users-permissions#licensespermissions
  promoted: false
- name: InsertAllowed
  value: "False"
  promoted: false
methods:
- syntax:
    content: 'procedure SetPlan(PlanId: Guid)'
    parameters:
    - id: PlanId
      parameterType:
        name: Guid
        isExternal: true
  name: SetPlan
  uid: M:Page::System#Azure#Identity#Plan_Configuration_Card.SetPlan(Guid)
commentId: O:Page::System#Azure#Identity#Plan Configuration Card
summary: Card page to show the permissions for a plan configuration.
name: '"Plan Configuration Card"'
uid: O:Page::System#Azure#Identity#Plan_Configuration_Card
