### YamlMime:BusinessCentralApplicationObject
fqName: System.Environment.Configuration.Checklist
alId: ID 1993
namespace: System.Environment.Configuration
baseKind: Page
kind: Page
parent: N:Module::System_Application::Namespace::System.Environment.Configuration
langs:
- al
sourceTableType:
  name: System.Environment.Configuration."Checklist Item Buffer"
  isExternal: true
seeAlso:
- '[Page](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-page-object)'
objectProperties:
- name: Caption
  value: Checklist Administration
  promoted: false
- name: ApplicationArea
  value: '#All'
  promoted: false
- name: PageType
  value: List
  promoted: true
- name: SourceTable
  value: "1995"
  promoted: true
- name: SourceTableTemporary
  value: "True"
  promoted: false
- name: UsageCategory
  value: Lists
  promoted: false
- name: Editable
  value: "True"
  promoted: false
- name: InsertAllowed
  value: "False"
  promoted: false
- name: ModifyAllowed
  value: "False"
  promoted: false
- name: RefreshOnActivate
  value: "True"
  promoted: false
commentId: O:Page::System#Environment#Configuration#Checklist
summary: Lists all checklist items and provides capabilities to edit and insert new ones based on existing guided experience items.
name: Checklist
uid: O:Page::System#Environment#Configuration#Checklist
