### YamlMime:BusinessCentralApplicationObject
fqName: System.Environment.Configuration."User Settings List"
alId: ID 9206
namespace: System.Environment.Configuration
baseKind: Page
kind: Page
parent: N:Module::System_Application::Namespace::System.Environment.Configuration
langs:
- al
seeAlso:
- '[Page](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-page-object)'
objectProperties:
- name: Caption
  value: User Settings
  promoted: false
- name: CardPageId
  value: User Personalization
  promoted: false
  xrefType:
    internalReference: O:Page::System#Environment#Configuration#User_Personalization
    name: System.Environment.Configuration."User Personalization"
    isExternal: false
- name: AdditionalSearchTerms
  value: User Personalization,User Preferences
  promoted: false
- name: UsageCategory
  value: Administration
  promoted: false
- name: ApplicationArea
  value: '#All'
  promoted: false
- name: Editable
  value: "False"
  promoted: false
- name: PageType
  value: List
  promoted: true
- name: SourceTable
  value: ""
  promoted: true
- name: SourceTableView
  value: sorting("User ID") order(ascending)
  promoted: false
- name: HelpLink
  value: https://go.microsoft.com/fwlink/?linkid=2149387
  promoted: false
- name: AboutTitle
  value: About user settings
  promoted: false
- name: AboutText
  value: '**User Settings** control the look and feel of the user interface the next time the users log in. Each user can also make their own choices in their **My Settings** page, unless you restrict their permissions.'
  promoted: false
commentId: O:Page::System#Environment#Configuration#User Settings List
summary: List page that shows the settings of all users.
name: '"User Settings List"'
uid: O:Page::System#Environment#Configuration#User_Settings_List
