### YamlMime:BusinessCentralApplicationObject
fqName: System.Environment.Configuration."Guided Experience Item Cleanup"
alId: ID 1998
namespace: System.Environment.Configuration
baseKind: Page
kind: Page
parent: N:Module::System_Application::Namespace::System.Environment.Configuration
langs:
- al
sourceTableType:
  name: System.Environment.Configuration."Guided Experience Item"
  isExternal: true
seeAlso:
- '[Page](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-page-object)'
objectProperties:
- name: ApplicationArea
  value: '#All'
  promoted: false
- name: Caption
  value: Duplicated Guided Experience Item Cleanup
  promoted: false
- name: SourceTableTemporary
  value: "True"
  promoted: false
- name: SourceTable
  value: "1990"
  promoted: true
- name: Editable
  value: "False"
  promoted: false
- name: InsertAllowed
  value: "False"
  promoted: false
- name: DeleteAllowed
  value: "False"
  promoted: false
- name: ModifyAllowed
  value: "False"
  promoted: false
- name: DataCaptionExpression
  value: "''"
  promoted: false
commentId: O:Page::System#Environment#Configuration#Guided Experience Item Cleanup
name: '"Guided Experience Item Cleanup"'
uid: O:Page::System#Environment#Configuration#Guided_Experience_Item_Cleanup
