### YamlMime:BusinessCentralApplicationObject
fqName: System Application by Microsoft (24.0.16410.19107)
baseKind: Module
kind: Module
objectProperties:
- name: Version
  value: 24.0.16410.19107
  promoted: false
- name: Publisher
  value: Microsoft
  promoted: false
- name: Brief
  value: Provides a standard set of capabilities that serve as a foundation for developing business apps.
  promoted: false
summary: Contains an expansive set of open source modules that make it easier to build, maintain, and easily upgrade on-premises and online apps. These modules let you focus on the business logic, and the needs of your users or customers.
name: System Application
uid: N:Module::System_Application
