### YamlMime:BusinessCentralApplicationObject
fqName: System.Environment.Configuration.BLANK
alId: ID -1
namespace: System.Environment.Configuration
baseKind: Profile
kind: Profile
parent: N:Module::System_Application::Namespace::System.Environment.Configuration
langs:
- al
seeAlso:
- '[Profile](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-profile-object)'
objectProperties:
- name: Caption
  value: Blank Profile
  promoted: false
- name: ProfileDescription
  value: This system profile should only be used to sign in when no other profiles are available.
  promoted: false
- name: RoleCenter
  value: Blank Role Center
  promoted: false
  xrefType:
    internalReference: O:Page::System#Environment#Configuration#Blank_Role_Center
    name: System.Environment.Configuration."Blank Role Center"
    isExternal: false
commentId: O:Profile::System#Environment#Configuration#BLANK
summary: Empty profile to use in case no other profile is present when system is initializing.
name: BLANK
uid: O:Profile::System#Environment#Configuration#BLANK
