### YamlMime:BusinessCentralApplicationObject
fqName: System.Environment.Configuration."User Settings"
alId: ID 9172
namespace: System.Environment.Configuration
baseKind: Table
kind: Table
parent: N:Module::System_Application::Namespace::System.Environment.Configuration
langs:
- al
seeAlso:
- '[Table](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-table-object)'
objectProperties:
- name: TableType
  value: Temporary
  promoted: false
- name: InherentEntitlements
  value: X
  promoted: false
- name: InherentPermissions
  value: X
  promoted: false
- name: DataClassification
  value: SystemMetadata
  promoted: false
fields:
- type:
    name: Guid
    isExternal: true
  name: '"User Security ID"'
  uid: F:Table::System#Environment#Configuration#User_Settings.User_Security_ID
- type:
    name: Code[50]
    isExternal: true
  name: '"User ID"'
  uid: F:Table::System#Environment#Configuration#User_Settings.User_ID[50]
- type:
    name: Boolean
    isExternal: true
  name: Initialized
  uid: F:Table::System#Environment#Configuration#User_Settings.Initialized
- type:
    name: Code[30]
    isExternal: true
  name: '"Profile ID"'
  uid: F:Table::System#Environment#Configuration#User_Settings.Profile_ID[30]
- type:
    name: Guid
    isExternal: true
  name: '"App ID"'
  uid: F:Table::System#Environment#Configuration#User_Settings.App_ID
- type:
    name: Option
    isExternal: true
  name: Scope
  uid: F:Table::System#Environment#Configuration#User_Settings.Scope
- type:
    name: Integer
    isExternal: true
  name: '"Language ID"'
  uid: F:Table::System#Environment#Configuration#User_Settings.Language_ID
- type:
    name: Text[30]
    isExternal: true
  name: Company
  uid: F:Table::System#Environment#Configuration#User_Settings.Company[30]
- type:
    name: Integer
    isExternal: true
  name: '"Locale ID"'
  uid: F:Table::System#Environment#Configuration#User_Settings.Locale_ID
- type:
    name: Text[180]
    isExternal: true
  name: '"Time Zone"'
  uid: F:Table::System#Environment#Configuration#User_Settings.Time_Zone[180]
- type:
    name: Date
    isExternal: true
  name: '"Work Date"'
  uid: F:Table::System#Environment#Configuration#User_Settings.Work_Date
- type:
    name: DateTime
    isExternal: true
  name: '"Last Login"'
  uid: F:Table::System#Environment#Configuration#User_Settings.Last_Login
- type:
    name: Boolean
    isExternal: true
  name: '"Teaching Tips"'
  uid: F:Table::System#Environment#Configuration#User_Settings.Teaching_Tips
- type:
    name: Boolean
    isExternal: true
  name: '"Legacy Action Bar"'
  uid: F:Table::System#Environment#Configuration#User_Settings.Legacy_Action_Bar
- type:
    name: Guid
    isExternal: true
  name: SystemId
  uid: F:Table::System#Environment#Configuration#User_Settings.SystemId
- type:
    name: DateTime
    isExternal: true
  name: SystemCreatedAt
  uid: F:Table::System#Environment#Configuration#User_Settings.SystemCreatedAt
- type:
    name: Guid
    isExternal: true
  name: SystemCreatedBy
  uid: F:Table::System#Environment#Configuration#User_Settings.SystemCreatedBy
- type:
    name: DateTime
    isExternal: true
  name: SystemModifiedAt
  uid: F:Table::System#Environment#Configuration#User_Settings.SystemModifiedAt
- type:
    name: Guid
    isExternal: true
  name: SystemModifiedBy
  uid: F:Table::System#Environment#Configuration#User_Settings.SystemModifiedBy
- type:
    name: BigInteger
    isExternal: true
  name: SystemRowVersion
  uid: F:Table::System#Environment#Configuration#User_Settings.SystemRowVersion
commentId: O:Table::System#Environment#Configuration#User Settings
summary: Temporary table that combines the settings defined by platform and application
name: '"User Settings"'
uid: O:Table::System#Environment#Configuration#User_Settings
