### YamlMime:BusinessCentralApplicationObject
fqName: System.Environment.Configuration."Feature Dependency"
alId: ID 2611
namespace: System.Environment.Configuration
baseKind: Table
kind: Table
parent: N:Module::System_Application::Namespace::System.Environment.Configuration
langs:
- al
seeAlso:
- '[Table](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-table-object)'
objectProperties:
- name: TableType
  value: Temporary
  promoted: false
- name: InherentEntitlements
  value: X
  promoted: false
- name: InherentPermissions
  value: X
  promoted: false
fields:
- type:
    name: Text[50]
    isExternal: true
  name: '"Feature Key"'
  uid: F:Table::System#Environment#Configuration#Feature_Dependency.Feature_Key[50]
- type:
    name: Text[50]
    isExternal: true
  name: '"Parent Feature Key"'
  uid: F:Table::System#Environment#Configuration#Feature_Dependency.Parent_Feature_Key[50]
- type:
    name: Guid
    isExternal: true
  name: SystemId
  uid: F:Table::System#Environment#Configuration#Feature_Dependency.SystemId
- type:
    name: DateTime
    isExternal: true
  name: SystemCreatedAt
  uid: F:Table::System#Environment#Configuration#Feature_Dependency.SystemCreatedAt
- type:
    name: Guid
    isExternal: true
  name: SystemCreatedBy
  uid: F:Table::System#Environment#Configuration#Feature_Dependency.SystemCreatedBy
- type:
    name: DateTime
    isExternal: true
  name: SystemModifiedAt
  uid: F:Table::System#Environment#Configuration#Feature_Dependency.SystemModifiedAt
- type:
    name: Guid
    isExternal: true
  name: SystemModifiedBy
  uid: F:Table::System#Environment#Configuration#Feature_Dependency.SystemModifiedBy
- type:
    name: BigInteger
    isExternal: true
  name: SystemRowVersion
  uid: F:Table::System#Environment#Configuration#Feature_Dependency.SystemRowVersion
commentId: O:Table::System#Environment#Configuration#Feature Dependency
summary: Temporary table stores pairs of the dependent features.
name: '"Feature Dependency"'
uid: O:Table::System#Environment#Configuration#Feature_Dependency
