### YamlMime:BusinessCentralApplicationObject
fqName: System.Apps."Extension Deployment Status"
alId: ID 2508
namespace: System.Apps
baseKind: Table
kind: Table
parent: N:Module::System_Application::Namespace::System.Apps
langs:
- al
seeAlso:
- '[Table](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-table-object)'
objectProperties:
- name: Caption
  value: Extension Deployment Status
  promoted: false
- name: TableType
  value: Temporary
  promoted: false
- name: InherentEntitlements
  value: RX
  promoted: false
- name: InherentPermissions
  value: RX
  promoted: false
- name: Extensible
  value: "False"
  promoted: true
fields:
- type:
    name: Guid
    isExternal: true
  name: '"Operation ID"'
  uid: F:Table::System#Apps#Extension_Deployment_Status.Operation_ID
- type:
    name: DateTime
    isExternal: true
  name: '"Started On"'
  uid: F:Table::System#Apps#Extension_Deployment_Status.Started_On
- type:
    name: Option
    isExternal: true
  name: '"Operation Type"'
  uid: F:Table::System#Apps#Extension_Deployment_Status.Operation_Type
- type:
    name: Option
    isExternal: true
  name: Status
  uid: F:Table::System#Apps#Extension_Deployment_Status.Status
- type:
    name: Blob
    isExternal: true
  name: Details
  uid: F:Table::System#Apps#Extension_Deployment_Status.Details
- type:
    name: Text[250]
    isExternal: true
  name: Description
  uid: F:Table::System#Apps#Extension_Deployment_Status.Description[250]
- type:
    name: Guid
    isExternal: true
  name: SystemId
  uid: F:Table::System#Apps#Extension_Deployment_Status.SystemId
- type:
    name: DateTime
    isExternal: true
  name: SystemCreatedAt
  uid: F:Table::System#Apps#Extension_Deployment_Status.SystemCreatedAt
- type:
    name: Guid
    isExternal: true
  name: SystemCreatedBy
  uid: F:Table::System#Apps#Extension_Deployment_Status.SystemCreatedBy
- type:
    name: DateTime
    isExternal: true
  name: SystemModifiedAt
  uid: F:Table::System#Apps#Extension_Deployment_Status.SystemModifiedAt
- type:
    name: Guid
    isExternal: true
  name: SystemModifiedBy
  uid: F:Table::System#Apps#Extension_Deployment_Status.SystemModifiedBy
- type:
    name: BigInteger
    isExternal: true
  name: SystemRowVersion
  uid: F:Table::System#Apps#Extension_Deployment_Status.SystemRowVersion
commentId: O:Table::System#Apps#Extension Deployment Status
summary: This temporary table is used to mirror the "NAV App Tenant Operation" system table and present details about the extension deployment status.///
name: '"Extension Deployment Status"'
uid: O:Table::System#Apps#Extension_Deployment_Status
