### YamlMime:BusinessCentralApplicationObject
fqName: System.Text."Barcode Encode Settings 2D"
alId: ID 9204
namespace: System.Text
baseKind: Table
kind: Table
parent: N:Module::System_Application::Namespace::System.Text
langs:
- al
seeAlso:
- '[Table](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-table-object)'
objectProperties:
- name: Access
  value: Public
  promoted: false
- name: Extensible
  value: "True"
  promoted: true
- name: TableType
  value: Temporary
  promoted: false
- name: InherentEntitlements
  value: X
  promoted: false
- name: InherentPermissions
  value: X
  promoted: false
- name: DataClassification
  value: SystemMetadata
  promoted: false
fields:
- description: Error Correction Level option used by QR code symbology.
  type:
    name: Option
    isExternal: true
  name: '"Error Correction Level"'
  uid: F:Table::System#Text#Barcode_Encode_Settings_2D.Error_Correction_Level
- description: Module Size option used by QR code symbology.
  type:
    name: Integer
    isExternal: true
  name: '"Module Size"'
  uid: F:Table::System#Text#Barcode_Encode_Settings_2D.Module_Size
- description: Quite Zone Width option used by QR code symbology.
  type:
    name: Integer
    isExternal: true
  name: '"Quite Zone Width"'
  uid: F:Table::System#Text#Barcode_Encode_Settings_2D.Quite_Zone_Width
- description: Code Page option used by QR code symbology.
  type:
    name: Integer
    isExternal: true
  name: '"Code Page"'
  uid: F:Table::System#Text#Barcode_Encode_Settings_2D.Code_Page
- type:
    name: Guid
    isExternal: true
  name: SystemId
  uid: F:Table::System#Text#Barcode_Encode_Settings_2D.SystemId
- type:
    name: DateTime
    isExternal: true
  name: SystemCreatedAt
  uid: F:Table::System#Text#Barcode_Encode_Settings_2D.SystemCreatedAt
- type:
    name: Guid
    isExternal: true
  name: SystemCreatedBy
  uid: F:Table::System#Text#Barcode_Encode_Settings_2D.SystemCreatedBy
- type:
    name: DateTime
    isExternal: true
  name: SystemModifiedAt
  uid: F:Table::System#Text#Barcode_Encode_Settings_2D.SystemModifiedAt
- type:
    name: Guid
    isExternal: true
  name: SystemModifiedBy
  uid: F:Table::System#Text#Barcode_Encode_Settings_2D.SystemModifiedBy
- type:
    name: BigInteger
    isExternal: true
  name: SystemRowVersion
  uid: F:Table::System#Text#Barcode_Encode_Settings_2D.SystemRowVersion
commentId: O:Table::System#Text#Barcode Encode Settings 2D
summary: Common setting used when encoding 2D barcodes.
name: '"Barcode Encode Settings 2D"'
uid: O:Table::System#Text#Barcode_Encode_Settings_2D
